name: lppet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/perrito.jpg
    - assets/perfil.png
    - assets/home/usuario.png
    - assets/home/perros.png
    - assets/home/gato_saludando.png
    - assets/home/adopcion.png
    - assets/home/donacion.png
    - assets/home/solicitud.png
